version: 2
updates:
  - package-ecosystem: docker
    directory: /deploy/goer
    schedule:
      interval: monthly
      day: sunday
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: sunday
    open-pull-requests-limit: 10
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
      day: sunday
    open-pull-requests-limit: 10
