---
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gocheckcompilerdirectives
    - gocyclo
    - godot
    - gofumpt
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - importas
    - ineffassign
    - makezero
    - mirror
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tenv
    - testableexamples
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
linters-settings:
  misspell:
    locale: US
  usestdlibvars:
    crypto-hash: true
    http-method: false
    os-dev-null: true
    sql-isolation-level: true
    time-layout: true
    tls-signature-scheme: true
