name: Build and test

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.3"

      - name: Build and test
        run: make build check tidy check-dirty
